export enum CARMASTER_EVENT_TYPES {
  NEW_CARMASTER_MESSAGE = 'NEW_MESSAGE',
  NEW_CARMASTER_MESSAGING = 'NEW_MESSAGING',
  CARMASTER_MESSAGING_EVENTS_SUBSCRIBED = 'MESSAGING_EVENTS_SUBSCRIBED',
  CARMASTER_MESSAGING_EVENTS_UNSUBSCRIBED = 'MESSAGING_EVENTS',
  TO_CARMASTER_MESSAGING_ROOM = 'TO_CARMASTER_MESSAGING_ROOM',

  JOIN_TO_CARMASTER_MESSAGING_ROOM = 'JOIN_TO_MESSAGING_ROOM',
  LEAVE_TO_CARMASTER_MESSAGING_ROOM = 'LEAVE_TO_MESSAGING_ROOM',
  CARMASTER_MESSAGE_TYPING = 'MESSAGE_TYPING',
  CARMASTER_MESSAGE_TYPING_STOPPED = 'MESSAGE_TYPING_STOPPED',

  CREDENTIAL_REPORTED = 'CREDENTIAL_REPORTED',
}

export enum CARMASTER_NOTIFICATION_TARGET_TYPES {
  MECHANIC = 'MECHANIC',
  SERVICE = 'SERVICE',
  CREDENTIAL = 'CREDENTIAL',
  SERVICE_REQUEST = 'SERVICE_REQUEST',
}
