export enum CARMASTER_EVENT_TYPES {
  NEW_CARMASTER_MESSAGE = 'NEW_CARMASTER_MESSAGE',
  NEW_CARMASTER_MESSAGING = 'NEW_CARMASTER_MESSAGING',
  CARMASTER_MESSAGING_EVENTS_SUBSCRIBED = 'CARMASTER_MESSAGING_EVENTS_SUBSCRIBED',
  CARMASTER_MESSAGING_EVENTS_UNSUBSCRIBED = 'CARMASTER_MESSAGING_EVENTS',
  TO_CARMASTER_MESSAGING_ROOM = 'TO_CARMASTER_MESSAGING_ROOM',

  JOIN_TO_CARMASTER_MESSAGING_ROOM = 'JOIN_TO_CARMASTER_MESSAGING_ROOM',
  LEAVE_TO_CARMASTER_MESSAGING_ROOM = 'LEAVE_TO_CARMASTER_MESSAGING_ROOM',
  CARMASTER_MESSAGE_TYPING = 'CARMASTER_MESSAGE_TYPING',
  CARMASTER_MESSAGE_TYPING_STOPPED = 'CARMASTER_MESSAGE_TYPING_STOPPED',

  CREDENTIAL_REPORTED = 'CREDENTIAL_REPORTED',

  NEW_SERVICE_REQUEST_OFFER = 'NEW_SERVICE_REQUEST_OFFER',
  SERVICE_REQUEST_OFFER_CANCELED = 'SERVICE_REQUEST_OFFER_CANCELED',
  SERVICE_REQUEST_OFFER_ACCEPTED = 'SERVICE_REQUEST_OFFER_ACCEPTED',
  SERVICE_REQUEST_OFFER_REJECTED = 'SERVICE_REQUEST_OFFER_REJECTED',

  SERVICE_REQUEST_MECHANIC_CANCELED = 'SERVICE_REQUEST_MECHANIC_CANCELED',
  SERVICE_REQUEST_USER_CANCELED = 'SERVICE_REQUEST_USER_CANCELED',

  NEW_SERVICE_REQUEST_MESSAGE = 'NEW_SERVICE_REQUEST_MESSAGE',
  NEW_SERVICE_REQUEST_DISPUTE = 'NEW_SERVICE_REQUEST_DISPUTE',
  NEW_SERVICE_REQUEST_DISPUTE_LOG = 'NEW_SERVICE_REQUEST_DISPUTE_LOG',
}

export enum CARMASTER_NOTIFICATION_TARGET_TYPES {
  MECHANIC = 'MECHANIC',
  SERVICE = 'SERVICE',
  CREDENTIAL = 'CREDENTIAL',
  SERVICE_REQUEST = 'SERVICE_REQUEST',
  SERVICE_REQUEST_DISPUTE = 'SERVICE_REQUEST_DISPUTE',
}


export enum CARMASTER_SERVICE_REQUEST_STATUSES {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  DISPUTED = 'DISPUTED',
  RESOLVED = 'RESOLVED',
}